name: Test suite

on:
  workflow_dispatch:
  pull_request:
    branches: ['develop', 'master']
    paths:
      - '.github/workflows/testsuite.yml'
      - 'superdsm/**'
      - 'examples/**'
      - 'superdsm.yml'
      - 'tests/**'
      - 'requirements.txt'

jobs:

  run_testsuite:
    name: Test suite
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
