name: Validate pull request

on:
  pull_request:

jobs:

  validate_conditional_checks:
    name: Validate conditional checks
    timeout-minutes: 1440
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04

    steps:

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y ca-certificates
    
      - name: Wait for test suite
        uses: blend/require-conditional-status-checks@2022.02.04
        with:
          interval: 20s
          timeout: 1440m
          checks-yaml: |
            - job: 'Thing1'
              paths:
                - .github/workflows/thing1.yml
                - thing1/**
            - job: 'Thing2'
              paths:
                - .github/workflows/thing2.yml
                - thing2/**
            - job: 'Thing3'
              paths:
                - .github/workflows/thing3.yml
                - thing3/**
